### ISSUE TITLE
http://demo.plone.de/en/demo is broken

### ISSUE THREAD

**Issue by sneridagh** [collective/demo.plone.de#11]
Something happen with the default view (summary_view) apparently related to Pillow (?) and the zexp file. The DE folder is fine.
```
  Module plone.namedfile.scaling, line 326, in scale
  Module plone.scale.storage, line 166, in scale
  Module plone.scale.storage, line 187, in _cleanup
  Module persistent.mapping, line 59, in __delitem__
  Module UserDict, line 25, in __delitem__
KeyError: (('direction', 'thumbnail'), ('fieldname', 'image'), ('height', 768), ('width', 768))

 - Expression: "python:scales.scale('image', 'thumb')"
 - Filename:   ... ne/app/contenttypes/browser/templates/listing_summary.pt
 - Location:   (line 34: col 36)
 - Source:     scale python:scales.scale('image', 'thumb')"
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
```

**Comment by pbauer** [comment]
@sneridagh thanks, I saw it thanks to sentry. My guess is ``plone.app.upgrade.v50.final.refresh_getIcon_catalog_metadata`` ignored the english news item since it does not use ``Language=''all"``in the query. I'll investigate.

**Comment by pbauer** [comment]
I fixed it by removing the old news item, adding a new one and creating a fresh zexp from that. So the demo-site works now but I fear the upgrade-issue still exists. I'll create a ticket in CMFPlone once I find time to confirm.
