### ISSUE TITLE
First load of the demo site (just after start the instance) returns escaped HTML

### ISSUE THREAD

**Issue by sneridagh** [collective/demo.plone.de#13]
The response's Content-Type is "application/javascript". No clue what causes this. Only happens on the first load of the site just after starting the instance, all later requests are ok.

Downgrading Plone to 5.0.2 solves the problem, 5.0.3 still have it.

![screen shot 2016-05-09 at 11 50 33](https://cloud.githubusercontent.com/assets/486927/15109570/45ae483a-15dc-11e6-84c3-f1fa7cebb986.png)

**Comment by pbauer** [comment]
Darn. Downgrading? Never gonna happen! @sneridagh Can you point me to the plone-issue that causes it?

**Comment by sneridagh** [comment]
@pbauer I could not reproduce it in a Vanilla Plone site :( I had a huntch on Multilingual, but still works there.

During the development of the new plone.org we had several issues with 5.0.4 resource registries and we had to go for a 5.1a version to fix them, so I thought that it would be related to it.

Maybe it's something related to the initial setup of the site and some interaction with 5.0.4 resource registries flaws.

**Comment by pbauer** [comment]
We work around this for now by loading the page after recreating the site with wget. I'm sure it'll be gone in 5.1
