### ISSUE TITLE
Show warning page during refresh

### ISSUE THREAD

**Issue by pbauer** [collective/demo.plone.de#20]
Every 4 hours the site is rebuilt. During that time (about 30 seconds) people will get error-messages. 
Instead we should switch nginx to display a static page with this info during that time. That shoudl be easy with fabric.

Also: it would be nice to display the time until the next rebuild so people get a fair warning. Something javascripty or something in python?

**Comment by tkimnguyen** [comment]
How about just changing your error 502 page to say something like "The site is being refreshed. Please check back in 15 minutes." or something to that effect?

**Comment by tkimnguyen** [comment]
Something like this in nginx.conf? 

    error_page 502 /path/of/custom/error/file;

**Comment by tkimnguyen** [comment]
Slick! Thanks for working out how to do it 👍 I was poking around unsuccessfully.
