### ISSUE TITLE
Serve Plone demo sites over https

### ISSUE THREAD

**Issue by stevepiercy** [collective/demo.plone.de#39]
From:
https://community.plone.org/t/serve-plone-demo-sites-over-https/10294

> All the demos that are linked from the [Try Plone](https://plone.com/try-plone.html) page do not run over https.
> 
> Given that security is one of the most promoted features of Plone, and that search engines have been dinging non-https sites for a while, I think it would be good to add https whenever possible to the demo sites.

**Comment by Gomez** [comment]
Fixed with moving the server.
