### ISSUE TITLE
How <div "principal plonedemo" role="complementary">

### ISSUE THREAD

**Issue by moacirviana** [collective/demo.plone.de#41]
How can I edit the text content found inside at <div "principal plonedemo" role="complementary"> ??

**Comment by pbauer** [comment]
That's hard-coded for the demo-site only and not mean to be edited. See https://github.com/collective/demo.plone.de/blob/master/src/plonedemo.site/src/plonedemo/site/browser/templates/frontpage_viewlet.pt
A default vanilla Plone site does not have this viewlets.
