### ISSUE TITLE
add gitter-chat

### ISSUE THREAD

**Issue by pbauer** [collective/demo.plone.de#6]
Use https://sidecar.gitter.im/

**Comment by jensens** [comment]
be aware of gitterHQ/sidecar#32

**Comment by pbauer** [comment]
@jensens thanks. Keep me updated if you find a way to resolve this.

**Comment by pbauer** [comment]
Done with https://github.com/collective/demo.plone.de/commit/112896447dbdacf881417e482353c285cad68683
@jensens
